
name: CI - Static analysis
on:
  push:
    branches:
      - step4
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sast:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}  # auto-provided
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

